<a href="https://colab.research.google.com/github/garfield-gray/DataMining/blob/main/Classification_%26_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Theoretical

#Imperical

In [2]:
# Address of files
%cd /content/drive/MyDrive/Uni/Data/DataMining/Winter2024/CA#4
!ls

/content/drive/MyDrive/Uni/Data/DataMining/Winter2024/CA#4
 CA4.pdf   CA#4Report.docx  'Classification_&_ML.ipynb'   Question_1.csv   Question_2.csv


##Queton_1

###Load

In [3]:
df = pd.read_csv('Question_1.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61069 entries, 0 to 61068
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Unnamed: 0            61069 non-null  int64  
 1   cap-diameter          61069 non-null  float64
 2   cap-shape             61069 non-null  object 
 3   cap-surface           46949 non-null  object 
 4   cap-color             61069 non-null  object 
 5   does-bruise-or-bleed  61069 non-null  object 
 6   gill-attachment       51185 non-null  object 
 7   gill-spacing          36006 non-null  object 
 8   gill-color            61069 non-null  object 
 9   stem-height           61069 non-null  float64
 10  stem-width            61069 non-null  float64
 11  stem-root             9531 non-null   object 
 12  stem-surface          22945 non-null  object 
 13  stem-color            61069 non-null  object 
 14  veil-type             3177 non-null   object 
 15  veil-color         

###Preprocessing

In [4]:
df['class'].unique()

array(['p', 'e'], dtype=object)

In [ ]:
for i in df.columns:
  print(df[i].unique())

[    0     1     2 ... 61066 61067 61068]
[15.26 16.6  14.07 ... 22.85 21.8  20.42]
['x' 'f' 'p' 'b' 'c' 's' 'o']
['g' 'h' nan 't' 'y' 'e' 's' 'l' 'd' 'w' 'i' 'k']
['o' 'e' 'n' 'g' 'r' 'w' 'y' 'p' 'u' 'b' 'l' 'k']
['f' 't']
['e' nan 'a' 'd' 's' 'x' 'p' 'f']
[nan 'c' 'd' 'f']
['w' 'n' 'p' 'u' 'b' 'g' 'y' 'r' 'e' 'o' 'k' 'f']
[16.95 17.99 17.8  ...  1.23  1.16  0.  ]
[17.09 18.19 17.74 ... 32.59 30.99 30.51]
['s' nan 'b' 'r' 'c' 'f']
['y' nan 's' 'k' 'i' 'h' 't' 'g' 'f']
['w' 'y' 'n' 'u' 'b' 'l' 'r' 'p' 'e' 'k' 'g' 'o' 'f']
['u' nan]
['w' 'y' nan 'n' 'e' 'u' 'k']
['t' 'f']
['g' 'p' 'e' 'l' 'f' 'm' nan 'r' 'z']
[nan 'w' 'p' 'k' 'r' 'u' 'n' 'g']
['d' 'm' 'g' 'h' 'l' 'p' 'w' 'u']
['w' 'u' 'a' 's']
['p' 'e']


####A

In [5]:

missing_values_count = df.isnull().sum()


data_types = df.dtypes


missing_info = pd.concat([missing_values_count, data_types], axis=1)
missing_info.columns = ['Missing Values', 'Data Type']

print(missing_info)


                      Missing Values Data Type
Unnamed: 0                         0     int64
cap-diameter                       0   float64
cap-shape                          0    object
cap-surface                    14120    object
cap-color                          0    object
does-bruise-or-bleed               0    object
gill-attachment                 9884    object
gill-spacing                   25063    object
gill-color                         0    object
stem-height                        0   float64
stem-width                         0   float64
stem-root                      51538    object
stem-surface                   38124    object
stem-color                         0    object
veil-type                      57892    object
veil-color                     53656    object
has-ring                           0    object
ring-type                       2471    object
spore-print-color              54715    object
habitat                            0    object
season       

In [7]:
df.isnull().mean()

Unnamed: 0              0.000000
cap-diameter            0.000000
cap-shape               0.000000
cap-surface             0.231214
cap-color               0.000000
does-bruise-or-bleed    0.000000
gill-attachment         0.161850
gill-spacing            0.410405
gill-color              0.000000
stem-height             0.000000
stem-width              0.000000
stem-root               0.843931
stem-surface            0.624277
stem-color              0.000000
veil-type               0.947977
veil-color              0.878613
has-ring                0.000000
ring-type               0.040462
spore-print-color       0.895954
habitat                 0.000000
season                  0.000000
class                   0.000000
dtype: float64

####B

In [8]:
import pandas as pd
from sklearn.impute import SimpleImputer

# Assuming 'df' is your DataFrame containing the dataset

# Step 1: Set the threshold
threshold = 0.5  # Example threshold of 50% missing values

# Step 2: Drop columns where the proportion of missing values exceeds the threshold
columns_to_drop = df.columns[df.isnull().mean() > threshold]
df_dropped = df.drop(columns=columns_to_drop)

# Step 3: Identify numerical and categorical columns
numerical_columns = df_dropped.select_dtypes(include=['number']).columns
categorical_columns = df_dropped.select_dtypes(include=['object', 'category']).columns

# Step 4: Impute missing values in numerical columns
numerical_imputer = SimpleImputer(strategy='mean')
df_imputed_numerical = pd.DataFrame(numerical_imputer.fit_transform(df_dropped[numerical_columns]), columns=numerical_columns)

# Step 5: Impute missing values in categorical columns
categorical_imputer = SimpleImputer(strategy='most_frequent')
df_imputed_categorical = pd.DataFrame(categorical_imputer.fit_transform(df_dropped[categorical_columns]), columns=categorical_columns)

# Step 6: Concatenate imputed numerical and categorical columns
df_imputed = pd.concat([df_imputed_numerical, df_imputed_categorical], axis=1)

# Verify the result
print("Original DataFrame shape:", df.shape)
print("DataFrame shape after dropping columns:", df_dropped.shape)
print("DataFrame shape after imputation:", df_imputed.shape)


Original DataFrame shape: (61069, 22)
DataFrame shape after dropping columns: (61069, 17)
DataFrame shape after imputation: (61069, 17)


In [31]:
df_imputed['cap-shape'].value_counts()

cap-shape
x    26934
f    13404
s     7164
b     5694
o     3460
p     2598
c     1815
Name: count, dtype: int64

In [32]:
pd.get_dummies(df_imputed['cap-shape'])

b      c      f      o      p      s      x
0      False  False  False  False  False  False   True
1      False  False  False  False  False  False   True
2      False  False  False  False  False  False   True
3      False  False   True  False  False  False  False
4      False  False  False  False  False  False   True
...      ...    ...    ...    ...    ...    ...    ...
61064  False  False  False  False  False   True  False
61065  False  False   True  False  False  False  False
61066  False  False  False  False  False   True  False
61067  False  False   True  False  False  False  False
61068  False  False  False  False  False   True  False

[61069 rows x 7 columns]

####C

In [29]:
# Using pandas' get_dummies function for one-hot encoding
df_encoded = pd.get_dummies(df_imputed, columns=categorical_columns)

In [33]:
df_encoded

Unnamed: 0  cap-diameter  stem-height  stem-width  cap-shape_b  \
0             0.0         15.26        16.95       17.09        False   
1             1.0         16.60        17.99       18.19        False   
2             2.0         14.07        17.80       17.74        False   
3             3.0         14.17        15.77       15.98        False   
4             4.0         14.64        16.53       17.20        False   
...           ...           ...          ...         ...          ...   
61064     61064.0          1.18         3.93        6.22        False   
61065     61065.0          1.27         3.18        5.43        False   
61066     61066.0          1.27         3.86        6.37        False   
61067     61067.0          1.24         3.56        5.44        False   
61068     61068.0          1.17         3.25        5.45        False   

       cap-shape_c  cap-shape_f  cap-shape_o  cap-shape_p  cap-shape_s  ...  \
0            False        False        False        False        False  ...   
1            False        False        False        False        False  ...   
2            False        False        False        False        False  ...   
3            False         True        False        False        False  ...   
4            False        False        False        False        False  ...   
...            ...          ...          ...          ...          ...  ...   
61064        False        False        False        False         True  ...   
61065        False         True        False        False        False  ...   
61066        False        False        False        False         True  ...   
61067        False         True        False        False        False  ...   
61068        False        False        False        False         True  ...   

       habitat_m  habitat_p  habitat_u  habitat_w  season_a  season_s  \
0          False      False      False      False     False     False   
1          False      False      False      False     False     False   
2          False      False      False      False     False     False   
3          False      False      False      False     False     False   
4          False      False      False      False     False     False   
...          ...        ...        ...        ...       ...       ...   
61064      False      False      False      False      True     False   
61065      False      False      False      False      True     False   
61066      False      False      False      False     False     False   
61067      False      False      False      False     False     False   
61068      False      False      False      False     False     False   

       season_u  season_w  class_e  class_p  
0         False      True    False     True  
1          True     False    False     True  
2         False      True    False     True  
3         False      True    False     True  
4         False      True    False     True  
...         ...       ...      ...      ...  
61064     False     False    False     True  
61065     False     False    False     True  
61066      True     False    False     True  
61067      True     False    False     True  
61068      True     False    False     True  

[61069 rows x 95 columns]

####D

In [51]:
from sklearn.preprocessing import StandardScaler

# Initialize StandardScaler
scaler = StandardScaler()

# Apply Z-score scaling to numerical columns
df_normalized = pd.DataFrame(scaler.fit_transform(df_encoded[numerical_columns]), columns=numerical_columns)

In [52]:
# Concatenate normalized numerical features with encoded categorical features
df_final = pd.concat([df_normalized, df_encoded.drop(columns=numerical_columns)], axis=1)

# Display the final dataset
df_final['cap-diameter'].min()


-1.206855392497904

In [53]:
df_final = df_final.drop(columns = 'Unnamed: 0')
df_final

cap-diameter  stem-height  stem-width  cap-shape_b  cap-shape_c  \
0          1.619462     3.076705    0.492293        False        False   
1          1.873982     3.385311    0.601900        False        False   
2          1.393432     3.328931    0.557061        False        False   
3          1.412426     2.726555    0.381690        False        False   
4          1.501699     2.952075    0.503254        False        False   
...             ...          ...         ...          ...          ...   
61064     -1.054903    -0.786809   -0.590822        False        False   
61065     -1.037808    -1.009362   -0.669539        False        False   
61066     -1.037808    -0.807581   -0.575875        False        False   
61067     -1.043506    -0.896602   -0.668543        False        False   
61068     -1.056802    -0.988590   -0.667546        False        False   

       cap-shape_f  cap-shape_o  cap-shape_p  cap-shape_s  cap-shape_x  ...  \
0            False        False        False        False         True  ...   
1            False        False        False        False         True  ...   
2            False        False        False        False         True  ...   
3             True        False        False        False        False  ...   
4            False        False        False        False         True  ...   
...            ...          ...          ...          ...          ...  ...   
61064        False        False        False         True        False  ...   
61065         True        False        False        False        False  ...   
61066        False        False        False         True        False  ...   
61067         True        False        False        False        False  ...   
61068        False        False        False         True        False  ...   

       habitat_m  habitat_p  habitat_u  habitat_w  season_a  season_s  \
0          False      False      False      False     False     False   
1          False      False      False      False     False     False   
2          False      False      False      False     False     False   
3          False      False      False      False     False     False   
4          False      False      False      False     False     False   
...          ...        ...        ...        ...       ...       ...   
61064      False      False      False      False      True     False   
61065      False      False      False      False      True     False   
61066      False      False      False      False     False     False   
61067      False      False      False      False     False     False   
61068      False      False      False      False     False     False   

       season_u  season_w  class_e  class_p  
0         False      True    False     True  
1          True     False    False     True  
2         False      True    False     True  
3         False      True    False     True  
4         False      True    False     True  
...         ...       ...      ...      ...  
61064     False     False    False     True  
61065     False     False    False     True  
61066      True     False    False     True  
61067      True     False    False     True  
61068      True     False    False     True  

[61069 rows x 94 columns]

####E

In [57]:
df_final['class_e'].value_counts()

class_e
False    33888
True     27181
Name: count, dtype: int64

In [58]:
# it's been decided to work with this dataset but we may change our mind!

###Classification

####A

####B

####C

####D

##Queton_2

###Load

In [ ]:
rawdata = pd.read_csv('Question_2.csv')
rawdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3650 entries, 0 to 3649
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    3650 non-null   object 
 1   Temp    3650 non-null   float64
dtypes: float64(1), object(1)
memory usage: 57.2+ KB


###Data Creation